### PR TITLE
Update LICENSE year and org name

### PR DESCRIPTION
**Pull request by rahulkumaran**
Solves #16

### CODE REVIEW

**Comment by rahulkumaran** [comment]
Hey, can someone review this?

**Comment by campoy** [comment]
I'm not sure this is something that needs to be changed, and if it does it needs to be changed in every single one of our repos (and others, like https://github.com/google/pprof/blob/master/LICENSE)

I'll let @smola review

**Comment by smola** [comment]
@campoy I don't think it should be updated there, since that's just an appendix of the license with instructions on how to apply licensing headers, not our license notice or header itself.

**Comment by campoy** [comment]
Ok, then

Thanks for the contribution @rahulkumaran but apparently the license is already fine as is.

But again, thanks for contributing! Looking forward to reviewing your next patches 🎉

**Pull request closed without merging**
